model_architecture:
  actfunc:
  - sigmoid
  batch_size: null
  layers:
  - 7
  - 10
  - 1
training:
  delta: 0.1
  delta_external: 0.001
  delta_synthetic: 0.0
  epsilon_synthetic: 0.0
  epsilon: 0.2
  learning_rate: 0.01
  monotone_relations:
  - 0
  - -1
  - -1
  - -1
  - 0
  - 0
  - 0
  n_epochs: 10000
  patience: 1000
  plot_history: True
  save_model: True
  early_stopping: True
  delta_early_stopping: 0.0
  std_growth: 0.0
  verbose: 1
  weight_decay: 0.0007
  seed: 0
  optimizer_type: 'Adam'